config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#                     posts GET    /posts(.:format)                                                                         posts#index
#                           POST   /posts(.:format)                                                                         posts#create
#                  new_post GET    /posts/new(.:format)                                                                     posts#new
#                 edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                      post GET    /posts/:id(.:format)                                                                     posts#show
#                           PATCH  /posts/:id(.:format)                                                                     posts#update
#                           PUT    /posts/:id(.:format)                                                                     posts#update
#                           DELETE /posts/:id(.:format)                                                                     posts#destroy
#                  comments POST   /comments(.:format)                                                                      comments#create
#                      root GET    /                                                                                        posts#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admin_users, controllers: {
    sessions:      'admin_users/sessions',
    passwords:     'admin_users/passwords',
    registrations: 'admin_users/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :posts
  resources :comments, only: [ :create, :destroy ]
  resources :users, only: :show

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  caption     :text(65535)      not null
#  user_id     :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  likes_count :integer
#

class Post < ApplicationRecord
  # モデル毎に表示する数が決まっている場合は定数にすることもできる
  paginates_per 5

  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  attribute :new_image
  validates :caption, presence: true
  validate :new_image_check


  def new_image_check
    ##### 中身を確認 #####
    if new_image.present?
      ##### ファイルの種類をチェック #####
      unless new_image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:new_image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      unless image.attached?
        errors.add(:new_image, 'ファイルを添付してください')
      end
    end
  end

  before_save do
    self.image = new_image if new_image
  end

  scope :find_newest_post, -> (page) { with_attached_image.order(created_at: :desc).page(page) }
  scope :with_user_and_comment, -> { includes(:comments, user: {avatar_attachment: :blob}, comments: :user) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :edit, :update, :destroy]

  def index
    # @q = Post.ransack(params[:q])
    # @posts = @q.result.find_newest_post(params[:page]).with_user_and_comment
    @comment = Comment.new
  end


  def new
    @post = Post.new # フォーム用の空のインスタンスを生成する。
  end

  def create# ストロングパラメータを引数に
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: "投稿を登録しました。"
    else
      render :new
    end
  end

  def show
    @post = Post.with_attached_image.includes(comments: :user).find(params[:id])
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "投稿を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました。"
  end

  private

  def post_params # ストロングパラメータを定義する
    params.require(:post).permit(:caption, :new_image, :user_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_icon_link(class_name)
    if user_signed_in?
      link_to user_path(current_user), class: class_name do
        content_tag(:i, "", class: "far fa-user")
      end
    else
      link_to new_user_session_path, class: class_name do
        content_tag(:i, "", class: "far fa-user")
      end
    end
  end
end

app/views/posts/_delete_modal.html.erb
<div class="modal fade" id="delete-post">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">投稿削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= image_tag @post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "img-fluid" %></p>
        <p><%= "削除しますか？" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post, local:true do |f| %>
  <%= render "shared/errors", obj: post %>
  <div class="form-group">
    <%= f.label :new_image %>
    <%= f.file_field :new_image, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, class: "form-control", rows: "7" %>
  </div>
  <p>
    <%= f.submit t(".post"), class: "btn btn-block btn-primary" %>
  </p>
  <p>
    <%= link_to t(".back"), :back, class: "btn btn-block btn-secondary" %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div class="card mb-5">
  <div class="card-header bg-transparent">
    <%= link_to user_path(post.user) do %>
      <% if post.user.avatar.attached? %>
        <%= image_tag post.user.avatar.variant(combine_options: { resize: "32x32^", crop: "32x32+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
      <% else %>
        <%= image_tag "no_image", class: "img-fluid rounded-circle" %>
      <% end %>
      <%= post.user.name %>
    <% end %>
  </div>
  <%= link_to post do %>
    <!-- mini_magickのメソッドを使用して画像サイズを変更して表示 -->
    <% if post.image.attached? %>
      <%= image_tag post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
    <% else %>
      <%= image_tag "no_image", class: "card-img" %>
    <% end %>
  <% end %>
  <%= render 'likes/like', post: post %>
  <div class="card-text">
    <p><%= truncate(post.caption, length: 90) %></p>

    <hr>

    <% post.comments.last(3).each_with_index do |comment, index| %>
      <p>
        <%= image_tag comment.user.avatar.variant(combine_options: { resize: "20x20^", crop: "20x20+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
        <%= comment.user.name %>
        <%= truncate(comment.body, length: 30) %>
        <% if current_user.id == comment.user.id %>
          <%= link_to t(".delete"), comment_path(comment), method: :delete, data: {confirm: '削除してよろしいですか？'} %>
        <% end %>
      </p>
    <% end %>

    <%= form_with model: @comment, url: comments_path, class: "form-group row mx-auto ", local: true do |f| %>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.text_field :body, class: "col-8 form-control" %>
      <%= f.submit t(".submit"), class: "col-4" %>
    <% end %>

  </div>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-lg-10 mx-auto">
    <div class="logo col-lg-12 mb-3 text-center">
      <h1>Edit Post</h1>
    </div>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-lg-6">
          <% if @post.image.attached? %>
            <%= image_tag @post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
          <% else %>
            <%= image_tag "no_image", class: "card-img" %>
          <% end %>
        </div>

        <div class="col-lg-6 card-cody">
          <%= render "form", post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="col-8 mx-auto">
  <%= render "shared/errors", obj: @comment %>
  <div class="post">
    <%= render @posts %>
    <%= paginate @posts %>
  </div>
</div>

<script>
  $(window).on('scroll', function() {
      // 画面スクロールの判定用の変数を用意
      scrollHeight = $(document).height();
      scrollPosition = $(window).height() + $(window).scrollTop();

      // 画面のスクロールが下部10%以下になったら
      if ( (scrollHeight - scrollPosition) / scrollHeight <= 0.1) {
        // .postに対し、jscrollを発火
        $('.post').jscroll({
          // 読込中の表示
          loadingHtml: '<div class="text-center"><img src="http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_48.gif">読み込み中</div>',
          // 読み込む内容があるリンク
          nextSelector: 'span.next a',
          // 読み込む内容がある場所
          contentSelector: '.post',
        });
      }
  });
</script>

app/views/posts/new.html.erb
<div class="col-lg-6 mx-auto">
  <div class="logo mb-3 text-center">
    <h1><%= t ".title" %></h1>
  </div>
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="col-lg-10 mx-auto">
  <div class="card">
    <div class="row no-gutters">
      <div class="col-lg-8">
        <% if @post.image.attached? %>
          <%= image_tag @post.image.variant(combine_options: { resize: "800x800^", crop: "800x800+0+0", gravity: :center }).processed, class: "card-img" %>
        <% else %>
          <%= image_tag "no_image", class: "card-img" %>
        <% end %>
      </div>
      <div class="col-lg-4">
        <div class="card-body">
          <%= image_tag @post.user.avatar.variant(combine_options:{ resize: "32x32^", crop: "32x32+0+0", gravity: :center }).processed, class: "img-thumbnail rounded-circle" %>
          <%= @post.user.name %>
          <hr>
          <div class="scroll">
            <% @post.comments.each do |comment| %>
              <p>
                <%= image_tag comment.user.avatar.variant(combine_options: { resize: "20x20^", crop: "20x20+0+0", gravity: :center }).processed, class: "img-fluid rounded-circle" %>
                <%= comment.user.name %>
                <%= comment.body %>
              </p>
            <% end %>
          </div>

          <%= form_with model: @comment, url: comments_path, class: "row mx-auto ", local: true do |f| %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :body, class: "col-8 form-control" %>
            <%= f.submit t(".submit"), class: "col-4" %>
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <p>
      <%= link_to t(".edit"), edit_post_path(@post), method: :get, class: "btn btn-block btn-primary" %>
    </p>
    <p>
      <%= button_tag t(".delete"), class: "btn btn-block btn-warning", data: { toggle: "modal", target: "#delete-post" } %>
    </p>
  <% end %>
</div>  


<%= render "delete_modal" , post: @post %>